name: Keep Streamlit App Alive
on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://gpt-prosociality-app.streamlit.app/
